### PR TITLE
Initialize HPET driver in DebugPort

### LINKED ISSUE #500: qemu-q35 debug port print breaks boot
When running `make run` for qemu-q35 I can not get past the first print onto the debug port [here](https://github.com/oreboot/oreboot/blob/main/src/mainboard/emulation/qemu-q35/src/main.rs#L30-L32). 

When this line is commented out I can at least get up to loading the payload (L47), at which a panic will occur and the following message will be printed forever:
```
Welcome to oreboot                                                                                       
boot flag is ffff, not aa55, at ffff,                                                                                                                                                                              
                                                                                                                                                                                                                   
PANIC: Welcome to oreboot                                                                                                                                                                                          
boot flag is ffff, not aa55, at ffff,                                                                                                                                                                              
                                                                                                         
PANIC: Welcome to oreboot                                                                                                                                                                                          
boot flag is ffff, not aa55, at ffff,
```

Hopefully I will be able to resolve it myself, but maybe someone knows whats wrong here :)

### PR DESCRIPTION
**Pull request by derpsteb**
Add a function `enable()` to the HPET driver. This allows the calling driver, `DebugPort` in this case, enable the timer if it wants to use it. This is necessary for the qemu-q35 board as it does not init the timer, like the romecrb board for example.
This fixes #500.

I was contemplating whether `hpet0()` should do this automatically, but as the code is already used in other boards and there is a comment saying the caller should ensure enablement I felt like this is sensible solution. Happy to hear other opinions.

### CODE REVIEW

File: src/drivers/timer/src/hpet.rs [hunk 1]
```diff
@@ -82,6 +83,16 @@ impl HPET {
         self.base as *const _
     }
 
+    pub fn enable(&self) -> Result<(), &str> {
+        // set enable bit for HPET timer as per 2.3.5
+        // https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/software-developers-hpet-spec-1-0a.pdf
+        self.config.set(1);
```
Comment (Rwantare) [inline src/drivers/timer/src/hpet.rs:89]: Instead of doing a raw set, you can use `config.modify(CONFIG::TMREN::SET)` since Danny already defined the type on L63

Comment (derpsteb) [reply src/drivers/timer/src/hpet.rs:89]: I have to take a closer look at this tock_registers crate. Looks great, thanks!

Comment (derpsteb) [reply src/drivers/timer/src/hpet.rs]: Resolved. Danny showed me another trick, which is great.

File: src/drivers/uart/src/debug_port.rs [hunk 2]
```diff
@@ -20,8 +20,8 @@ impl<D: Driver> DebugPort<D> {
 }
 
 impl<D: Driver> Driver for DebugPort<D> {
-    // Nothing to set up here
     fn init(&mut self) -> Result<()> {
+        self.timer.enable().unwrap();
```
Comment (daym) [inline src/drivers/uart/src/debug_port.rs]: Probably makes more sense to `map_err` here. `unwrap` would just fail the program on error.

**Review by rminnich — APPROVED** [review]

**Review by daym — DISMISSED** [review]

**Comment by rminnich** [comment]
you should be able to run 
make format
locally from top of tree to catch formatting issues

**Comment by derpsteb** [comment]
yeah I still have to develop the habit :(

**Review by daym — APPROVED** [review]
